// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW3ipphUW7NIkGNo6nanCPxSDChf7QpXE',
    appId: '1:479120284842:web:ca2a60631aaaa68e2104d3',
    messagingSenderId: '479120284842',
    projectId: 'chatapp-71442',
    authDomain: 'chatapp-71442.firebaseapp.com',
    storageBucket: 'chatapp-71442.appspot.com',
    measurementId: 'G-1MS9ZGKSTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVr2v-c_RGJsklaecirTIZpcYaSG__ycg',
    appId: '1:479120284842:android:693b0bbfb976638b2104d3',
    messagingSenderId: '479120284842',
    projectId: 'chatapp-71442',
    storageBucket: 'chatapp-71442.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY_A5PsLc2oW5rocCCzTjT80b__1OLEUA',
    appId: '1:479120284842:ios:b828f4ba4a715e202104d3',
    messagingSenderId: '479120284842',
    projectId: 'chatapp-71442',
    storageBucket: 'chatapp-71442.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY_A5PsLc2oW5rocCCzTjT80b__1OLEUA',
    appId: '1:479120284842:ios:ee99a3897c066c922104d3',
    messagingSenderId: '479120284842',
    projectId: 'chatapp-71442',
    storageBucket: 'chatapp-71442.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
